const products = [
    {
      id: 0,
      name: "Pistolet Smith & Wesson M&P9 M2.0",
      description: `Masa:	700g, Kaliber:	9mm luger, Długość:	18,8cm, Magazynek:	17-nabojowy`,
      category: "Broń krótka",
      price: 2949.99,
      image: "\obrazy/pistolet1.png",
      sale: true,
      saleAmount: 200,
    },
    {
      id: 1,
      name: "Pistolet GLOCK 17 Gen 3",
      description: `Masa:	710g, Kaliber:	9mm luger, Długość:	20,4cm, Magazynek:	17-nabojowy`,
      category: "Broń krótka",
      price: 3290.00,
      image: "\obrazy/pistolet2.jpg",
    },
    {
      id: 2,
      name: "Pistolet WALTHER P-99",
      description: `Masa:	698 g, Kaliber:	19 mm, Długość:	18cm, Magazynek:	15-nabojowy`,
      category: "Broń krótka",
      price: 2800.00,
      image: "\obrazy/pistolet3.jpg",
    
    },
    {
      id: 3,
      name: "Karabin TAURUS T4",
      description: `Masa:	3020 g, Kaliber:	45 mm, Długość:	87,3cm, Magazynek:	30-nabojowy`,
      category: "Broń długa",
      price: 7499.00,
      image: "\obrazy/karabin1.jpg",
    },
    {
      id: 4,
      name: "Karabin Smith & Wesson M&P-15",
      description: `Masa:	2966 g, Kaliber:	5,56x45 NATO, Długość:	94cm, Magazynek:	30-nabojowy`,
      category: "Broń długa",
      price: 6599.00,
      image: "\obrazy/karabin2.jpg",
      sale: true,
      saleAmount: 100,
    },
    {
      id: 5,
      name: "Karabin OOW M249",
      description: `Masa:	8242 g, Kaliber:	5,56x45 NATO, Długość:	104cm, Magazynek:	M27 Taśmowany`,
      category: "Broń długa",
      price: 11500.00,
      image: "\obrazy/karabin3.jpg",
    },
    {
      id: 6,
      name: "Strzelba Samopowtarzalna AKSA S4",
      description: `Masa:	3847 g, Kaliber:	12GA, Długość:	87cm, Magazynek:	7+1-nabojowy`,
      category: "Strzelby",
      price: 4599.00,
      image: "\obrazy/strzelba1.jpg",
    },
    {
      id: 7,
      name: "Strzelba FABARM Martial O. D. Green",
      description: `Masa:	2970 g, Kaliber:	12/76, Długość:	64cm, Magazynek:	5+1-nabojowy`,
      category: "Strzelby",
      price: 3500.00,
      image: "\obrazy/strzelba2.png",
    },
    {
      id: 8,
      name: "Strzelba FABARM SDASS ProTelescopic Stage 2",
      description: `Masa:	3440 g, Kaliber:	12/76, Długość:	82cm, Magazynek:	7+1-nabojowy`,
      category: "Strzelby",
      price: 5499.00,
      image: "\obrazy/strzelba3.jpg",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 9,
      name: "Karabin Snajperski BARRETT MRAD kal. 338 Lapua Magnum",
      description: `Masa:	6600 g, Kaliber:	.338 lapua mag, Długość:	125,5cm, Magazynek:	10-nabojowy`,
      category: "Broń Wyborowa",
      price: 44900.00,
      image: "\obrazy/snajperka1.jpg",
    },
  ];